### ISSUE TITLE
Basic Information app fails to open + autodetect token speed issue

### ISSUE THREAD

**Issue by Stendarpaval** [Nazrax/fvtt-movement-planner#1]
Hi there! I really like this module, as it might really speed up combat for my table. Unfortunately, I ran into some bugs in 0.1.2.

1. The first bug occurs when trying to open the Basic Information settings menu / FormApplication from Combat Range Overlay's module settings. It doesn't open, and instead this error shows up in the console:

<img width="703" alt="combat-range-overlay-screenshot-1" src="https://user-images.githubusercontent.com/17188192/125581089-727ccf7a-12d1-4aa1-96da-e8a0c8f7cd4e.png">
(By the way, I named my data folder "foundrydatadev" in order to differentiate it from "foundrydata". It really shouldn't be the cause of any problems, or at least I'd be very surprised if it was)
<br>
<br>

2. The other problem I'm having is that this warning notification shows up every time I select a token:
<img width="930" alt="combat-range-overlay-screenshot-2" src="https://user-images.githubusercontent.com/17188192/125581336-f82d025c-f06f-4985-8e3e-682ce8002b95.png">

The notifications go away when I disable Combat Range Overlay, so I'm pretty sure this is caused by Combat Range Overlay (not 100% because the console remains quiet). All tokens I tested this with have properly filled in movement speeds, so that can't be it. I'm using dnd5e's 5/10/5 ft. distance option, in case that's relevant.

That reminds me, I'm running on Foundry Core 0.8.8 using the dnd5e system 1.3.6. 

Let me know if you need any other info :)

**Comment by AdrianAbraham** [comment]
I've pushed a new release containing the missing template, and I'm looking into the speed warning.

**Comment by AdrianAbraham** [comment]
Ok, 0.1.4 should have both fixes.

**Comment by Stendarpaval** [comment]
Just checked, and indeed both issues are solved. Thanks for the quick fix!
