### ISSUE TITLE
images are missing

### ISSUE THREAD

**Issue by cpcodes** [Nazrax/fvtt-movement-planner#4]
The readme and the module itself depend on images from https://media.githubusercontent.com/media/Nazrax/fvtt-combat-range-overlay/media/images, but all of those links appear to be broken. As such, there is no indication as to what the activation button is (https://media.githubusercontent.com/media/Nazrax/fvtt-combat-range-overlay/media/images/button.png, the alt text is simply "the button") and multiple errors are generated in the console log when the module is active.

**Comment by AdrianAbraham** [comment]
I've moved the images from Github to Imgur, and I'm fetching small versions - hopefully I won't hit any more bandwidth limits ...
